# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='objetivo',
            field=models.CharField(blank=True, choices=[(b'Nueva visita', b'Nueva visita')], max_length=40, null=True),
        ),
    ]
