# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_objetivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='objetivo',
        ),
    ]
