# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.CharField(choices=[(b'Raul Rodriguez', b'Raul Rodriguez'), (b'El Viejo', b'El Viejo')], max_length=30)),
                ('insurance', models.CharField(choices=[(b'ARS Humano', b'ARS Humano'), (b'ARS Palic', b'ARS Palic'), (b'Universal', b'Universal'), (b'SeNaSa', b'SeNaSa'), (b'Seguros Banreservas', b'Seguros Banreservas')], max_length=40)),
                ('observaciones', models.CharField(max_length=500)),
                ('diagnosis', models.TextField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
