# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20161022_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='patient',
            new_name='paciente',
        ),
    ]
