# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20161022_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.CharField(choices=[(b'', b'-- Seleccionar --'), (b'Raul Rodriguez', b'Raul Rodriguez'), (b'Dr. Vasquez', b'Dr. Vasquez')], max_length=30),
        ),
    ]
