# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_auto_20161113_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='diagnosis',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cita',
            name='insurance',
            field=models.CharField(choices=[(b'', b'-- Seleccionar --'), (b'ARS Humano', b'ARS Humano'), (b'ARS Palic', b'ARS Palic'), (b'Universal', b'Universal'), (b'SeNaSa', b'SeNaSa'), (b'Seguros Banreservas', b'Seguros Banreservas'), (b'Privado', b'Privado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.CharField(max_length=5000),
        ),
    ]
