# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0008_remove_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(blank=True, choices=[(b'', b'-- Seleccionar --'), (b'Raul Rodriguez', b'Raul Rodriguez'), (b'Dr. Vasquez', b'Dr. Vasquez')], max_length=45, null=True)),
                ('antecedentes_personales', models.TextField(blank=True, max_length=500, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, max_length=500, null=True)),
                ('enfermedad_actual', models.TextField(blank=True, max_length=500, null=True)),
                ('signos_sintomas', models.TextField(blank=True, max_length=500, null=True)),
                ('rehab_diagnosis', models.TextField(blank=True, max_length=500, null=True)),
                ('protocol_treatment', models.TextField(blank=True, max_length=500, null=True)),
                ('form_filled_by', models.TextField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
