# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('full_name', models.CharField(max_length=60)),
                ('id_card_number', models.CharField(max_length=45)),
                ('sex', models.CharField(choices=[(b'Hombre', b'Hombre'), (b'Mujer', b'Mujer')], max_length=5)),
                ('age', models.CharField(max_length=3)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('cellphone', models.IntegerField()),
                ('other_phone', models.IntegerField()),
                ('occupation', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('placeofwork', models.CharField(max_length=45)),
                ('work_phone', models.IntegerField()),
                ('insurancecompany', models.CharField(choices=[(b'ARS Humano', b'ARS Palic'), (b'ARS Palic', b'ARS Palic'), (b'Universal', b'Universal'), (b'SeNaSa', b'SeNaSa'), (b'Seguros Banreservas', b'Seguros Banreservas')], max_length=35)),
                ('refered_by', models.CharField(max_length=45)),
                ('in_case_of_emergency_contact', models.CharField(max_length=45)),
                ('emergency_contact_phone', models.IntegerField()),
                ('emergency_contact_cellphone', models.IntegerField()),
                ('emergency_contact_othernum', models.IntegerField()),
                ('form_filled_by', models.CharField(max_length=45)),
                ('doctor', models.CharField(choices=[(b'Raul Rodriguez', b'Raul Rodriguez'), (b'El Viejo', b'El Viejo')], max_length=45)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
