# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.CharField(choices=[(b'', b'-- Seleccionar --'), (b'Raul Rodriguez', b'Raul Rodriguez'), (b'El Viejo', b'El Viejo')], max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurancecompany',
            field=models.CharField(choices=[(b'', b'-- Seleccionar --'), (b'ARS Humano', b'ARS Humano'), (b'ARS Palic', b'ARS Palic'), (b'Universal', b'Universal'), (b'SeNaSa', b'SeNaSa'), (b'Seguros Banreservas', b'Seguros Banreservas')], max_length=35),
        ),
    ]
