# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20161022_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
