# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20161022_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='antecedentes_personales',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enfermedad_actual',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='protocol_treatment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rehab_diagnosis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='signos_sintomas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
