# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20161113_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='antecedentes_familiares',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antecedentes_personales',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='enfermedad_actual',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='form_filled_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='protocol_treatment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rehab_diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='signos_sintomas',
        ),
    ]
