# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cellphone',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_cellphone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_othernum',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='in_case_of_emergency_contact',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_phone',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='patient',
            name='placeofwork',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='position',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
