# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20161116_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cellphone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='other_phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
