# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20161116_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurancecompany',
            field=models.CharField(choices=[(b'', b'-- Seleccionar --'), (b'ARS Humano', b'ARS Humano'), (b'ARS Palic', b'ARS Palic'), (b'Universal', b'Universal'), (b'SeNaSa', b'SeNaSa'), (b'Seguros Banreservas', b'Seguros Banreservas'), (b'Privado', b'Privado')], max_length=35),
        ),
    ]
